controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login_check
    controller: Symfony\Bundle\SecurityBundle\Controller\LoginController::login
    methods: POST
